<?php
/**
 * @file
 * Functions to support the mexant_theme theme.
 */



use Drupal\block\BlockPluginInterface;

/**
 * Implements hook_preprocess_block().
 */
function mexant_theme_preprocess_block(array &$variables) {
  if (
    isset($variables['elements']['#id']) &&
    $variables['elements']['#id'] === 'mexant_theme_copyright'
  ) {
    $rendered_content = \Drupal::service('renderer')
      ->renderPlain($variables['content']);

    $rendered_content = str_replace('{{year}}', date('Y'), $rendered_content);

    $variables['content'] = [
      '#markup' => $rendered_content,
    ];
  }
}

