<?php

/**
 * Implements hook_schema().
 */
function employee_api_schema() {

  $schema['employee'] = [

    'description' => 'Employee table',

    'fields' => [

      'eid' => [
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],

      'ename' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ],

      'doj' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
    ],

    'primary key' => ['eid'],
  ];

  return $schema;
}